inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest

AllCops:
  DisabledByDefault: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6
  Exclude:
    - 'docs/**/*'
    - 'examples/**/*'
    - 'vendor/bundle/**/*'

Layout:
  Enabled: true

Layout/CommentIndentation:
  AllowForAlignment: true

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Lint:
  Enabled: true

Minitest:
  Enabled: true

Style:
  Enabled: true
