name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 90
        days-before-close: -1
        stale-issue-message: >
          This issue has been automatically marked as stale because it has not been commented on for at least three months.

          If you have any new information or updates please reply in order to keep the issue open.
        stale-pr-message: >
          This pull request has been automatically marked as stale because has been no activity for at least three months.

          If you have any new information or updates please reply in order to keep the pull request open.
        stale-issue-label: stale
        stale-pr-label: stale
