name: Test
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test_ruby_versions:
    runs-on: ${{matrix.os || 'ubuntu-latest'}}

    continue-on-error: ${{ matrix.allow_failures == 'allow failures' || false }}

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}" ### allows adding gemfile: to the matrix, bundler will automatically pick this up

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - jruby-9.3
          - jruby-9.4
          - jruby-10.0
        include:
          - ruby: head
            allow_failures: 'allow failures'
          - ruby: jruby-head
            allow_failures: 'allow failures'
        exclude:
          - ruby: jruby-9.4
            os: windows-latest
          - ruby: truffleruby
            os: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rake
